version: "3.8"

services:

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-laravel-${APP_ENV}
    environment: 
      DB_DATABASE: ${DB_DATABASE}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: '3306'
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_URL: ${APP_URL}
      APP_DEBUG: ${APP_DEBUG}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      LOG_CHANNEL: ${LOG_CHANNEL}
    depends_on: 
      - mariadb
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html

  mariadb:
    image: mariadb:10.6
    container_name: ${APP_NAME}-mariadb-${APP_ENV}
    restart: always
    environment: 
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - data_volume:/var/lib/mysql

  npm:
    image: node:14
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

volumes:
  data_volume:
    name: ${VOLUME_NAME}